[2022-11-02T16:08:14.314+0700] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: postgres_dag.create_table scheduled__2022-11-01T00:00:00+00:00 [queued]>
[2022-11-02T16:08:14.323+0700] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: postgres_dag.create_table scheduled__2022-11-01T00:00:00+00:00 [queued]>
[2022-11-02T16:08:14.323+0700] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-02T16:08:14.323+0700] {taskinstance.py:1363} INFO - Starting attempt 1 of 6
[2022-11-02T16:08:14.323+0700] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-02T16:08:14.337+0700] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_table> on 2022-11-01 00:00:00+00:00
[2022-11-02T16:08:14.339+0700] {standard_task_runner.py:55} INFO - Started process 82419 to run task
[2022-11-02T16:08:14.343+0700] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'postgres_dag', 'create_table', 'scheduled__2022-11-01T00:00:00+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres.py', '--cfg-path', '/tmp/tmp5f22h1y3']
[2022-11-02T16:08:14.345+0700] {standard_task_runner.py:83} INFO - Job 47: Subtask create_table
[2022-11-02T16:08:14.399+0700] {task_command.py:376} INFO - Running <TaskInstance: postgres_dag.create_table scheduled__2022-11-01T00:00:00+00:00 [running]> on host ginraca-VirtualBox
[2022-11-02T16:08:14.445+0700] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=postgres_dag
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-01T00:00:00+00:00
[2022-11-02T16:08:14.449+0700] {base.py:71} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-11-02T16:08:14.466+0700] {sql.py:315} INFO - Running statement: 
            create table if not exists dag_runs(
                dt date,
                dag_id varchar,
                primary key (dt, dag_id)
            )
        , parameters: None
[2022-11-02T16:08:14.637+0700] {taskinstance.py:1401} INFO - Marking task as SUCCESS. dag_id=postgres_dag, task_id=create_table, execution_date=20221101T000000, start_date=20221102T090814, end_date=20221102T090814
[2022-11-02T16:08:14.675+0700] {local_task_job.py:164} INFO - Task exited with return code 0
[2022-11-02T16:08:14.685+0700] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
